---
- hosts: kvm 
  become: true
  vars_files:
    - vars/vms.yaml

  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk
      command: >
               virt-builder --format qcow2 centos-7.6
               -o {{ vm_location}}/{{ item.key }}.qcow2
               --root-password password:{{ root_pass }}
               --ssh-inject {{ ssh_user }} 
               --selinux-relabel
               --hostname {{ item.key }}.local
                
      when: item.key not in disks.stdout
      with_dict: "{{ guests }}"

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms 

    - name: create vm
      command: >
                virt-install --import --name {{ item.key }}
                --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
                --disk {{ vm_location }}/{{ item.key }}.qcow2
                --noautoconsole --os-variant centos7.0
                --network bridge={{ host_bridge }}
      when: item.key not in vms.list_vms
      with_dict: "{{ guests }}"

    - name: start vm
      virt:
        name: "{{ item.key }}"
        state: running
      with_dict: "{{ guests }}"
